# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c9fe3c4842d1e64c72fd8960c1f5ef88e24f6262444d0505311004d50c6913ccb808e8da1d74557070bb316972b3968a126fbcb2b5a092b19d53af6828aa93f

test:
  secret_key_base: 7a0d90e34520d74bef1b8f116aa8acecc1d3997b6ffa9e5269e0e9ea45f72c79cece019bb2c74be697824146bd6197b571dd4a0a9421d8b777e34dbd4291ffea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
